trigger:
  branches:
    include:
      - main
      
pr:
  branches:
    include:
      - main
  drafts: false
  
variables:
  projects: '**/*.sln'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install DotNet'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Build'
  inputs:
    command: 'build'
    projects: $(projects)
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'DotNet Drop'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Drop'
    publishLocation: 'Container'
    
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: '614e75a1-bd55-4ade-b0c3-e3246314b59d'
    appType: 'functionAppLinux'
    appName: 'a1ex'
    deployToSlotOrASE: true
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'